server.port=8080

# SQLite : le fichier est cree automatiquement dans Backend/data/
spring.datasource.url=jdbc:sqlite:./data/newapp.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
